### ISSUE TITLE
Standard Binary Serialization Format

### ISSUE THREAD

**Issue by mletterle** [Microsoft/xaml-standard#119]
Currently there are a multitude of serialization formats depending on the platform: BAML, XBF, or sometimes just plain XAML as an embedded resource. If people think having some sort of "compiled XAML" format is useful for performance it would be nice to have a standardized and documented binary format.

**Comment by insinfo** [comment]
@mletterle
It would not be better if the title were "Define a Standard Binary Format for XAML. BAML or XBF"

If possible visit my posts to help in defining the model and syntax of these controls
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/98), 
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/99), 
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/109), 
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/110), 
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/112), 
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/117),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/120),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/121),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/122),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/123),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/124),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/125),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/126),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/127),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/128),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/129),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/130),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/131),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/132),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/135),
[Visit this link](https://github.com/Microsoft/xaml-standard/issues/135),

**Comment by harinikmsft** [comment]
Serialization formats are upto the implementers of the standard. The XAML Standard is the specification and will not mandate compilation formats etc., This is beyond the scope.

**Comment by birbilis** [comment]
XAML Standard is supposed to help with interoperability though. Is this going to be only at the verbose level? Would be nice at least to also support a .Xamlz file extension (zipped .Xaml) in tooling and at XAML loaders

**Comment by Mike-EEE** [comment]
Agreed @birbilis.  @harinikmsft while I also agree this is beyond the _current_ scope, it would be nice to somehow incorporate this for _future_ offerings, and/or to at least capture it as a known request.  Maybe consider adding a "feature request" tag as well as a "discussion" tag? 

That way the community gets to talk about it as a captured/known item (and feel engaged/heard), while stakeholders can easily filter it from their reporting.

Anyways, something to think about.

**Comment by Mike-EEE** [comment]
And speaking of thinking about... the thought strikes me just as I post. 😉 

The other benefit to this is that you can capture the reactions (up/down/confused/etc) and get a good grasp of sentiment/importance on the matter as time goes on.  This assists with prioritization and the like.
