### ISSUE TITLE
Add WebView

### ISSUE THREAD

**Issue by insinfo** [Microsoft/xaml-standard#132]
A web view is a region that can display rich HTML content 

```xaml
<WebView URL="https://github.com/Microsoft/xaml-standard" Width="100%" Height="100%"/>
```

![web view 2](https://cloud.githubusercontent.com/assets/12227024/26272107/4f004586-3ce7-11e7-9fc7-b93d4d480c33.png)
![web view 3](https://cloud.githubusercontent.com/assets/12227024/26272108/4f1b867a-3ce7-11e7-91bb-95d09641b5e4.jpg)
![webview 1](https://cloud.githubusercontent.com/assets/12227024/26272109/4f2105b4-3ce7-11e7-9641-c2d3f67f0158.png)

**Comment by Duranom** [comment]
There is already a webview planned for XAML Standard 1.0, See [https://github.com/Microsoft/xaml-standard/issues/6](#6)
Unless you mean additional features, but would help to search a bit

**Comment by insinfo** [comment]
@Duranom 
Yes it's true, when I was going to post I looked if there was already this and for some reason I did not locate it.
On the other hand it is good because it reinforces the idea

**Comment by harinikmsft** [comment]
Already tracked by #6
