### ISSUE TITLE
Xamarin.Forms Feature Roadmap

### ISSUE THREAD

**Issue by monkeynoises** [Microsoft/xaml-standard#133]
Pin this....as if we know what features are coming, we know what can/can't be included in a standard.

https://forums.xamarin.com/discussion/85747/xamarin-forms-feature-roadmap

**Comment by jassmith** [comment]
The XAML Standard feature set is not limited to what Xamarin.Forms currently supports or will support in the future.

**Comment by weitzhandler** [comment]
@jassmith
I agree with what you said, but please include a roadmap in your wiki, to let people know what's your plans, and in what time frame you're planning any release.
