### ISSUE TITLE
Partnership with Adobe

### ISSUE THREAD

**Issue by insinfo** [Microsoft/xaml-standard#182]
The XAML standardization team, partner with Adobe to:
Here are two ideas:
1: Make the code behind Adobe XD be XAML, ie the file generated by Adobe XD be a XAML file, and Adobe support the definition of the XAML standard.
2: Since the code behind of Adobe XD is XAML, implement an exporter of UI elements to XAML, how this would work:

For example:
Let's imagine that you drew a rectangle with yellow rounded corners and added the following text in it "Login", right after you've grouped it, and now you want this to be a button, simply you click convert to button, and then click on toggle For XAML or click show XAML code and copy to clipboard, then you just paste the code in Xamarin.Forms in Visual Studio.
This would make life easier for millions of developers.
In addition, this will allow a greater prominence of XAML Standard, and greater acceptance in the market and in the media.

**Comment by Mike-EEE** [comment]
IIRC there were exporters for/in Adobe Illustrator for Xaml back in the day...

**Comment by monkeynoises** [comment]
Just give them the source code to Expression Designer, and let them Adobitize it, so it's familiar to Designers.

**Comment by crutkas** [comment]
This feels odd topic and not related to the standard.

**Comment by birbilis** [comment]
Indeed off-topic, however design tools integration is an issue indeed.

There are not enough good exporters from other tools to XAML (Mike Swanson had made an AI [Adobe Illustrator] to XAML exporter, but its output needed some tweaking to use in WPF/Silverlight) and is not maintained anymore from what I know.

Would be nice if the Expression Designer etc. had been released to opensource at least.

Speaking of opensource, after the XAML Standard 1.0 is released, the community and MS could focus a bit on XAML exporters for Inkscape etc. using Path like AI->XAML exporter did. And maybe exporters for tools that are pixel-focused too like Krita, Paint.net and other painting s/w - e.g. be able to export a layered image composition into a folder using XAML [for the layering composition effects] + a set of image files for each of the layers. Being able to export 2D animations from Krita to XAML would really nice too.

**Comment by Mike-EEE** [comment]
I've mentioned this a few times now but this repo could benefit from a "discussion" tag/label that can be applied to issues like this to help separate out more standards-related dialogue vs. (important and valuable) community-fostering/ideation activities.

**Comment by birbilis** [comment]
they've seemed to have started adding a "meta" tag which is probably appropriate to such items. But I'd rename this issue to "Design Tools integration" and probably check the initial text a bit since using XAML as internal format at an existing tool isn't an option I guess, but export/import support for both commercial and opensource design tools is feasible

**Comment by Mike-EEE** [comment]
yeah... meta/discussion, whatevs. :)  IMO running into a rather costly GitHub limitation here.  You would really think they would have solved the problem of people getting into threads/OT/etc from their single-threaded, ultra scroll format of SCROLLBARKNUB.

**Comment by crutkas** [comment]
if you guys tooling requests, please head to http://wpdev.uservoice.com and request please it with scenarios.
