### ISSUE TITLE
Create a XAML Designer Plugin for VSCode

### ISSUE THREAD

**Issue by MXM-7** [microsoft/xaml-standard#219]
Would be nice to be enable to edit Xaml code with a designer view in VSCode

**Comment by auahub** [comment]
then use visual studio proper
________________________________

**Comment by mdtauk** [comment]
I think there is scope to display a visual preview of a XAML page - like viewing HTML in a browser while looking at the markup in VS Code.  But it can't be an interactive display or WYSIWYG.  For that you need a full IDE

**Comment by MXM-7** [comment]
I was thinking about something similar to the very good **Ionide** for F# but for XAML.
You can still code F# in visual studio but with VSCode it's much more responsive and even less buged and the worst it get better and more feature than the official tool of microsoft. (This was the spirit , I'm codding a lot with visual studio , I like it but some times it so laguy :) )

**Comment by adebiyial** [comment]
I've been using visual studio code for more than three months now for all of my CS. Which means I use .NET core. Adding such huge undertaken will only overwhelm VSCode with lack of purpose. Use Blend if VS gets laggy.

**Comment by insinfo** [comment]
It could be a plugin as well so it would not let the Visual Studio Code slow and overloaded, in addition to Blend and Visual Studio Community does not have Designer support for Xamarin.Forms.

**Comment by DanielKorsah** [comment]
@adebiyial 
As a pluggin you can choose to have it or not. If you don't want it, it won't slow you down.

**Comment by kibiz0r** [comment]
Just having VSCode run `MSBuild:UpdateDesignTimeXaml` on save would be enough for me. I don't need a visual designer, or even XAML intellisense really. I just want Omnisharp's loaded symbols to keep up with my XAML changes.

**Comment by michael-hawker** [comment]
Forgot to come back and post here, feel free to check out the new Store App [XAML Studio](https://aka.ms/GetXAMLStudio) which is a rapid prototyping tool for UWP XAML.

**Comment by MXM-7** [comment]
@michael-hawker Thank you sounds great, Never thought that someone will even consider my request. UI is the last concern of developer ;) It's a microsoft garage project so I imagine it's open source? any link to the repo , can outside user can contritubute or report bugs or feature request?

**Comment by mdtauk** [comment]
While we are discussing this, can we get a better XAML designer for Visual Studio and Code? ;)

**Comment by MXM-7** [comment]
@mdtauk Actually I'm not aware of any xaml designer for visual studio code , but the main window of Xaml Studio  is very similar to VSCode

**Comment by michael-hawker** [comment]
@MXM-7 yeah, I based my design off of VS Code for the XAML Studio UX.

The project isn't open source yet.  I'm really the only person working on the project, outside of some assists during hackathons, so I didn't have the bandwidth to go through the extra process for Open Source yet.  It's on my list of things to do, you can [vote for it on UserVoice](https://microsoftgarage.uservoice.com/forums/918727-xaml-studio/suggestions/36548137-please-open-source-it).

**Comment by CrazyAlex25** [comment]
Аor those who decide to write a plugin, you can take [WpfDesigner](https://github.com/icsharpcode/WpfDesigner)

**Comment by CallumCarmicheal** [comment]
Are there any updates on this? WinForms and WPF is now supported in .NET Core making them both cross platform. 
https://devblogs.microsoft.com/dotnet/windows-forms-designer-for-net-core-released/

**Comment by michael-hawker** [comment]
@CallumCarmicheal WPF and WinForms aren't cross platform. While they work on top of .NET Core now, they still only work on Windows.

**Comment by mrghosti3** [comment]
Just wanted to say, there's a framework AvaloniaUI for C# .NET which allows you to make cross platform apps. So XAML visualizer on VS Code would indeed be usefull especially if there is devs that don't use Windows and would want be able to still see how their app looks without running it.

**Comment by michael-hawker** [comment]
FYI, there's also this project that's been started by @microhobby as well: https://github.com/microhobby/vs-code-uno-platform

**Comment by timheuer** [comment]
Hi there, closing this as not applicable to this repo's topic.  Please open VS Code suggestions on the https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=feature_request.md suggestion area repo.
