### ISSUE TITLE
Allow XAML to be used to describe UI which is output as HTML/JS underneath

### ISSUE THREAD

**Issue by monkeynoises** [Microsoft/xaml-standard#34]
This would enable "Fluent" interfaces to be described/developed in XAML, but then further integrating HTML behaviours/elements on top....and then a "site" could be browsed in any browser with lots of richness.

**Comment by lokitoth** [comment]
This seems more like an implementation detail of a given XAML Standard-supporting platform, than a question to be addressed at the Standard level.
