### ISSUE TITLE
Add Controls Deferred Loading

### ISSUE THREAD

**Issue by francedot** [Microsoft/xaml-standard#37]
## Deferred Loading
Port Deferred Loading Strategy of UWP to Xamarin.Forms.

```xml
<Grid x:DeferLoadStrategy="Lazy"/>
```

**Comment by bschoepke** [comment]
Dupe of #22

x:Load is the replacement for x:DeferLoadStrategy and adds support for unloading

**Comment by francedot** [comment]
@bschoepke Good to know. I didn't catch that API update..

**Comment by harinikmsft** [comment]
Dupe of #22
