### ISSUE TITLE
Define "Platform Optional" as a tag for features.

### ISSUE THREAD

**Issue by JeffLewisWA** [Microsoft/xaml-standard#50]
My proposal is to define the object's tag in the standard, with an flag saying 'Platform optional', which means you can choose not to implement it - but if you do, you must comply with the standard.

There will be some objects which make perfect sense on one platform, but then make no sense at all on another. The Menu object I mention in another issue is a good example of this.

Menu makes sense in WPF and Xamarin.Forms MacOS, but doesn't make as much sense in Xamarin.Forms Android, Xamarin.Forms iOS or UWP. On the other hand, those have 'Hamburger menus' which could share that object.

So I can see Menus implemented for some of these platforms, but not for others. It would be best if when Menu _is_ implemented, it's done consistently, with the standard Menu (and MenuItem) syntax being interpreted at implementation time to define the behaviour.

On platforms where the object doesn't make sense and isn't implemented, the XAML compiler should throw a warning that the object isn't supported on the target platform.

**Comment by mrlacey** [comment]
I believe this is covered in the [principles](https://github.com/Microsoft/xaml-standard/blob/staging/docs/reviewboard.md#principles), where it states

> The Standard may have annotations that allow types or P/M/Es to be optional. In these cases, the expectation is that they will be ignored by the frameworks that do not support them (they will not cause “unsupported” exceptions).

**Comment by JeffLewisWA** [comment]
Excellent! Then I consider this closed. Thank you for the information.
