### ISSUE TITLE
Make Blend for Visual Studio works for UWP & Xamarin

### ISSUE THREAD

**Issue by JimSEOW** [Microsoft/xaml-standard#56]
XAML how's works across mobile platforms as well as MacOS. We need Blend to be more integrated as part of Xamarin strategy: Live player, Xamarin Form Previewer, 

This complements Visual Studio For Mac strategy.

Pls make Blend for Visual Studio to work on Xamarin Form XAML !!!!!

**Comment by harinikmsft** [comment]
Thanks for the feedback. However, this is unrelated to XAML Standard specification. Please record your voice here instead - https://xamarin.uservoice.com/forums/144858-xamarin-platform-suggestions/suggestions/6716840-blend-for-xamarin
