### ISSUE TITLE
React-like philosophy for UI controls

### ISSUE THREAD

**Issue by Odonno** [Microsoft/xaml-standard#63]
Not mandatory, but it could be interesting to use the react philosophy to enabled "global One Way binding" on every UI control.

If enabled, it can ensure that every UI control should only use One Way binding and of course, all UI controls should work perfectly with this pattern.

**Comment by rodrigoelp** [comment]
Wouldn't that be a different framework? I want to understand correctly your proposal, what you would like XAML standard to implement is a process in which, your viewmodel is recreated with whatever property changes you did and sent to the presenter to recreate the view or update where it needs. Basically, having immutable viewmodels.

**Comment by Odonno** [comment]
@rodrigoelp I think it should be designed before everything else. My proposal is that UI controls, I mean their Dependency Properties can only be updated by a parent element. So the ViewModel can set properties but it should be the only one who can update the child properties.

I know there are some frameworks that implement Redux for example. What I really want is to avoid the side effects can happen when updating a property of an element can update a parent element. Of course, a UI element can update its own properties or even the properties of its children elements. The counterparts of not being able to update parent element is to handle events in the parent using the native event system, a Messaging service like in MVVM or even Redux.

**Comment by rodrigoelp** [comment]
@Odonno but the part I don't understand is the benefit of having it implemented directly in the standard.

I understand your point of view, most of these frameworks have been built on top of standards that already deal with side effects. This is one of those frameworks: https://github.com/GuillaumeSalles/redux.net

If you really want this proposal to understand, try to provide samples of what you would like to achieve and how it will make the standard better. Given I have seen lots of proposal along the lines of "make the new standard exactly the same as WPF so I don't need to change my code..." stating the benefits more than the wishes should enable more people to engage it.

**Comment by Odonno** [comment]
I made some tests and I agree that we should not modify the current behavior of controls. The UI controls can stick with the two-way binding and other frameworks can deal with it, whether it is MVC/MVVM-like or state-based architecture using Redux.
