### ISSUE TITLE
Ancestor Binding

### ISSUE THREAD

**Issue by ahoefling** [Microsoft/xaml-standard#64]
When I have used Ancestor Binding in WPF I found it super useful in many cases and missed this feature in Xamarin.Forms. I could see this being very helpful when you need to traverse the XAML to get ancestor objects. 

I'm curious on what other people think about this being int he standard. I have been able to work around the limitation but think it would be useful

**Comment by skendrot** [comment]
Possible duplicate of #27

**Comment by ahoefling** [comment]
Yup, it is a duplicate I will close this out

**Comment by mrlacey** [comment]
please add the duplicate label :)
