### ISSUE TITLE
Add TabItem control

### ISSUE THREAD

**Issue by Krzem0** [Microsoft/xaml-standard#67]

**Comment by birbilis** [comment]
maybe duplicate - there was another issue on Tabbed control

**Comment by skendrot** [comment]
Duplicate of #30

**Comment by mrlacey** [comment]
please add the duplicate label :)

**Comment by Krzem0** [comment]
I would, but I don't have this option. :|
https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/
http://i65.tinypic.com/b5oetf.jpg

**Comment by Odonno** [comment]
@mrlacey @Krzem0 Only moderators of this repository can apply labels.
