### ISSUE TITLE
Standard for Event Handler names

### ISSUE THREAD

**Issue by yeskunall** [Microsoft/xaml-standard#71]
Hey 👋

Me and our small team just started working on a cross-platform app using `C#` and Xamarin.Forms, so this repo couldn't drop at a better time!

I notice that the function called by the event handler for a [button](https://github.com/Microsoft/xaml-standard/blob/staging/docs/v1draft.md#1-button) is written as `MyButton_Click`. My mind immediately screamed at the way PascalCase was combined with snake_case &mdash; not that there's anything wrong with it &mdash; but judging from [this](https://msdn.microsoft.com/en-us/library/x2dbyw72(v=vs.71).aspx) resource, looks like `C#` doesn't use snake_case anywhere (correct me if I'm wrong tho) and I therefore think it should instead read `ClickMyButton`.

Please let me know what you think about this. ❤️

**Comment by dotMorten** [comment]
The event is called Click and is in the MyButton instance so there's no way to write it any other way but you're free to rename MyButton to whatever you want.

**Comment by MovGP0** [comment]
I use a strict `On` naming convention for all event handlers: 
```xaml
<Button x:Name="MyButton" Click="OnMyButton_Click" />
```

Note that the event (what has happened) should not do anything more than validation and invoking of an command (what will happen)

```csharp
public void OnMyButton_Click(object sender, EventArgs args)
{
   DoSomething.Execute(args);
}
```

**Comment by birbilis** [comment]
OnXXX (e.g. TButton.OnClick) is used in Delphi for (overridable) virtual methods of components that were responsible of checking if there is an event target and firing the event handler. The event handler can be an anonymous method or whatever, no need to have any extra convention for its naming, the current one is fine

**Comment by MovGP0** [comment]
@birbilis I only name the event handling procedure this way, never properties

**Comment by birbilis** [comment]
since you use MyButton in the name instead of Button guess it doesn't cause extra confusion

**Comment by MovGP0** [comment]
@birbilis the idea is that I can identify what it does and when it does it, just by looking at the name and without looking at the internals. This also makes it easier to find it when working on another part of the code. 

If it would be named `MyButtonClick` I'd assume a subclass of MyButton. With `ClickMyButton` I assume a command and not an event.

**Comment by GeraudFabien** [comment]
Nothinks to do with Xaml, C# or even dotnet. I feel like i sayed that on any comment i do on this repo.
For the explanation Visual alway autocomplete the name of even handler with the variable name and "_" and delegate/event name like this. VS Team try to make XAML feel like it's compile into normal C#. So they use the exact same rules. If it bother you maybe you should look at using MVVM pattern or just change the name before generating the method (The method is only generate when you click on F12 or DoubleClick). 
`
Timer myTimer = new Timer();
myTimer.Elapsed += myTimer_Elapsed;
`

**Comment by skendrot** [comment]
How the IDE auto names an event handler has nothing to do with the XAML Standard. This is best suited for the Visual Studio team.

**Comment by harinikmsft** [comment]
This is more about generated code convention than related to XAML Standard vocabulary specification.
