### ISSUE TITLE
Add TreeView control with hierarchical data binding

### ISSUE THREAD

**Issue by wieslawsoltes** [Microsoft/xaml-standard#87]
Add TreeView control with hierarchical data binding
```XAML
<TreeView Items="{Binding}">
    <TreeView.ItemTemplate>
        <TreeDataTemplate ItemsSource="{Binding Children}">
            <TextBlock Text="{Binding Header}"/>
        </TreeDataTemplate>
    </TreeView.ItemTemplate>
</TreeView>
```

**Comment by shengguow** [comment]
It would be better if the orientation of the TreeView's growth is customizable.

**Comment by MovGP0** [comment]
a redesign of the navigation to make it more web like usually removes the need for tree views. there are likely valid use cases for this but I can't think of one that can't be solved with a proper design.

**Comment by mossyblog** [comment]
I'll be honest the TreeView and DataGrid controls were deliberately witheld in Silverlight because they were being abused in Usage :)

Turns out you all found a way around them and it resulted in List controls being innovative ...

Imho i'd love to see these controls being purged from existence..especially ones that have TreeViews with Datagrids inside them.... why do you hate the user so much? WHYYY...

**Comment by birbilis** [comment]
Don't see why a hierarchical view is "bad" to have

**Comment by dotMorten** [comment]
That's just Scott. He likes to complain more than me 😂
Yes tree view has its issues but despite Scotts hating, lots and lots of enterprise scenarios expects them. We can guide people to a different UX but if the users have a good case for it (even if it's "we always did it like this") who are we to judge when they pay us?  Familiarity has its merits too.

**Comment by mossyblog** [comment]
@dotMorten a child expects sugar at every turn in a super market isle... doesn't mean you feed the child said sugar.

It's to do with task complexity, and the short version is they impose short-term memory load in which users fail to achieve said task(s) as the hierarchy expands deeper.  Effectively its a developer pattern enforced onto an audience that didn't seek or expect the experience in such a way, further to this point you're effectively emulating products like Microsoft Excel without the actual parity in said feature(s) most of the time. Instead you're invoking more developer cost(s) and expectations on the user therefore driving up likely production costs/times in areas that aren't likely to actually solve the intended problem that was originally first given.

Drag-n-Drop controls are blessing and a course, upside is you lean on that crutch the downside is you're not fully aware of whether or not the said control actually solved the said set of problems or are effectively useful in helping users navigate said problems with solutions.

"We can guide people to different UX" unless there is actual qualified research all you're effectively doing is advocating your personal bias / instincts. Research in Hierarchy / Expandable Indexes thus far do however underpin the position I'm taking in that the deeper you go, the less efficient and more tax you impose on the user.

But sure, go ahead with the composition of this idea and learn the hard way.. if at all you're actually iterating your experiences with users 👍 

I'm only complainy when i see the same mistake repeating over and over.. its frustrating :)

**Comment by birbilis** [comment]
People use mouse too btw, not just touch. 
And browsing a file system for example in win8 touch style was a real pain

**Comment by monkeynoises** [comment]
What a hierarchical tree view does, is allow you to drill down into something and backing out, without getting lost....you know what paths ahead are doable, and you know where you are at all times. "Places" in the tree are memorable too...as muscle memory

Breadcrumbs, etc...are fine when you have a limited set of paths you can take......or are not switching to different "continents" in your tree dataset.

Imagine "Explorer.exe" having 2 panels with "web navigation" in both sides - so many clicks to test whats in a route....and can't get a good overall picture of the hierarchy.

**Comment by asyncawaitmvvm** [comment]
If the source data is hierarchical, a tree of some sort is the only real option. Breaking that congruence is where the experience falls apart, when the user's ability to navigate the data mentally becomes worthless as a guide to navigate the UI physically. People have to get work done on these things you know.

I wrote a godmode clone of File Explorer in WPF lately. How was I going to do it without a tree control or drag and drop? Please make sure you're always aware of everyone you're handicapping. The tools that uber devs use... require the most advanced UI controls. The commoners want to use the same tools daddy uses in the garage, not these toys like hamburger menu. You know how it goes.

**Comment by birbilis** [comment]
btw, hierarchical data binding can also be used at drill-down views, acyclic graphs etc., not just trees. But does it need other infrastructure changes too in UWP/Xamarin.Forms to support such?

**Comment by birbilis** [comment]
since hierarchical data binding was mentioned, this is relevant from https://docs.microsoft.com/el-gr/windows/uwp/data-binding/how-to-bind-to-hierarchical-data-and-create-a-master-details-view

> You can make a multi-level master/details (also known as list-details) view of hierarchical data by binding items controls to CollectionViewSource instances that are bound together in a chain. In this topic we use the {x:Bind} markup extension where possible, and the more flexible (but less performant) {Binding} markup extension where necessary. 

wonder if x:Bind (https://github.com/Microsoft/xaml-standard/issues/19) supports hierarchical binding semantics or to make use of such one has always to use or combine with classic Binding. If it doesn't could it probably be extended with such semantics?

**Comment by monkeynoises** [comment]
Taking Visual Studio as an example....and imagining how it "may" transition to being a UWP or Xaramain.Forms app.....just how does the "don't have a treeview control" and use  the "web only hierarchical" idiom work exactly?

**Comment by birbilis** [comment]
indeed, especially in Solution Explorer pane

**Comment by arminlinder** [comment]
No having a standard Treeview control is, in my opinion, doing more bad than good.

Armin.
